export const nestedRegions = [
  {
    key: 'northIsland',
    label: 'North Island',
    subdivs: [
      {
        key: 'Northland',
        label: 'Northland Region',
        subdivs: [
          { key: 'Dargaville', label: 'Dargaville' },
          { key: 'Kaikohe', label: 'Kaikohe' },
          { key: 'Kaitaia', label: 'Kaitaia' },
          { key: 'Kawakawa', label: 'Kawakawa' },
          { key: 'Kerikeri', label: 'Kerikeri' },
          { key: 'Mangawhai', label: 'Mangawhai' },
          { key: 'Maungaturoto', label: 'Maungaturoto' },
          { key: 'Paihia', label: 'Paihia' },
          { key: 'Whangarei', label: 'Whangarei' },
        ],
      },
      {
        key: 'Auckland',
        label: 'Auckland Region',
        subdivs: [
          { key: 'Albany', label: 'Albany' },
          { key: 'AucklandCity', label: 'Auckland city' },
          { key: 'BotabyDowns', label: 'Botaby Downs' },
          { key: 'Clevedon', label: 'Clevedon' },
          { key: 'Franklin', label: 'Franklin' },
          { key: 'GreatBarrierIsland', label: 'Great Barrier Island' },
          { key: 'Helensville', label: 'Helensville' },
          { key: 'Henderson', label: 'Henderson' },
          { key: 'HibiscusCoast', label: 'Hibiscus Coast' },
          { key: 'Kumeu', label: 'Kumeu' },
          { key: 'Mangere', label: 'Mangere' },
          { key: 'Manukau', label: 'Manukau' },
          { key: 'NewLynn', label: 'New Lynn' },
          { key: 'NorthShore', label: 'North Shore' },
          { key: 'Onehunga', label: 'Onehunga' },
          { key: 'Papakura', label: 'Papakura' },
          { key: 'Pukekohe', label: 'Pukekohe' },
          { key: 'Remuera', label: 'Remuera' },
          { key: 'WaihekeIsland', label: 'Waiheke Island' },
          { key: 'Waitakere', label: 'Waitakere' },
          { key: 'Waiuku', label: 'Waiuku' },
          { key: 'Warkworth', label: 'Warkworth' },
          { key: 'Wellsford', label: 'Wellsford' },
        ],
      },
      {
        key: 'Waikato',
        label: 'Waikato Region',
        subdivs: [
          { key: 'Cambridge', label: 'Cambridge' },
          { key: 'Coromandel', label: 'Coromandel' },
          { key: 'Hamilton', label: 'Hamilton' },
          { key: 'Huntly', label: 'Huntly' },
          { key: 'Matamata', label: 'Matamata' },
          { key: 'Morrinsville', label: 'Morrinsville' },
          { key: 'Ngaruawahia', label: 'Ngaruawahia' },
          { key: 'Ngatea', label: 'Ngatea' },
          { key: 'Otorohanga', label: 'Otorohanga' },
          { key: 'Paeroa', label: 'Paeroa' },
          { key: 'Raglan', label: 'Raglan' },
          { key: 'Taumaranui', label: 'Taumaranui' },
          { key: 'Taupo', label: 'Taupo' },
          { key: 'TeAwamutu', label: 'Te Awamutu' },
          { key: 'TeKuiti', label: 'Te Kuiti' },
          { key: 'Thames', label: 'Thames' },
          { key: 'TokoroaPutaruru', label: 'Tokoroa/Putaruru' },
          { key: 'Turangi', label: 'Turangi' },
          { key: 'Waihi', label: 'Waihi' },
          { key: 'Whangamata', label: 'Whangamata' },
          { key: 'Whitianga', label: 'Whitianga' },
        ],
      },
      {
        key: 'BayPlenty',
        label: 'Bay of Plenty Region',
        subdivs: [
          { key: 'Katikati', label: 'Katikati' },
          { key: 'Kawerau', label: 'Kawerau' },
          { key: 'MtMaunganui', label: 'Mt Maunganui' },
          { key: 'Opotiki', label: 'Opotiki' },
          { key: 'Papamoa', label: 'Papamoa' },
          { key: 'Rotorua', label: 'Rotorua' },
          { key: 'Tauranga', label: 'Tauranga' },
          { key: 'TePuke', label: 'Te Puke' },
          { key: 'WaihiBeach', label: 'Waihi Beach' },
          { key: 'Whakatane', label: 'Whakatane' },
        ],
      },
      {
        key: 'Gisborne',
        label: 'Gisborne',
        subdivs: [
          { key: 'Gisborne', label: 'Gisborne' },
          { key: 'Ruatoria', label: 'Ruatoria' },
        ],
      },
      {
        key: 'HawkesBay',
        label: "Hawke's Bay District",
        subdivs: [
          { key: 'Hastings', label: 'Hastings' },
          { key: 'Napier', label: 'Napier' },
          { key: 'Waipukurau', label: 'Waipukurau' },
          { key: 'Wairoa', label: 'Wairoa' },
        ],
      },
      {
        key: 'Taranaki',
        label: 'Taranaki Region',
        subdivs: [
          { key: 'Hawera', label: 'Hawera' },
          { key: 'Mokau', label: 'Mokau' },
          { key: 'NewPlymouth', label: 'New Plymouth' },
          { key: 'Opunake', label: 'Opunake' },
          { key: 'Stratford', label: 'Stratford' },
        ],
      },
      {
        key: 'Whanganui',
        label: 'Whanganui Region',
        subdivs: [
          { key: 'Ohakune', label: 'Ohakune' },
          { key: 'Taihape', label: 'Taihape' },
          { key: 'Waiouru', label: 'Waiouru' },
          { key: 'Whanganui', label: 'Whanganui' },
        ],
      },

      {
        key: 'Manawatu',
        label: 'Manawatū-Whanganui Region',
        subdivs: [
          { key: 'Bulls', label: 'Bulls' },
          { key: 'Dannevirke', label: 'Dannevirke' },
          { key: 'Feilding', label: 'Feilding' },
          { key: 'Levin', label: 'Levin' },
          { key: 'Manawatu', label: 'Manawatu' },
          { key: 'Marton', label: 'Marton' },
          { key: 'Pahiatua', label: 'Pahiatua' },
          { key: 'Palmerston North', label: 'Palmerston North' },
          { key: 'Woodville', label: 'Woodville' },
        ],
      },

      {
        key: 'Wairarapa',
        label: 'Wairarapa Region',
        subdivs: [
          { key: 'Carterton', label: 'Carterton' },
          { key: 'Featherston', label: 'Featherston' },
          { key: 'Greytown', label: 'Greytown' },
          { key: 'Martinborough', label: 'Martinborough' },
          { key: 'Masterton', label: 'Masterton' },
        ],
      },
      {
        key: 'Wellington',
        label: 'Wellington Region',
        subdivs: [
          { key: 'Kapiti', label: 'Kapiti' },
          { key: 'LowerHuttCity', label: 'Lower Hutt City' },
          { key: 'Porirua', label: 'Porirua' },
          { key: 'UpperHuttCity', label: 'Upper Hutt City' },
          { key: 'WellingtonCity', label: 'Wellington City' },
        ],
      },
    ],
  },
  {
    key: 'southIsland',
    label: 'South Island',
    subdivs: [
      {
        key: 'NelsonBays',
        label: 'Nelson Bays Region',
        subdivs: [
          { key: 'GoldenBay', label: 'Golden Bay' },
          { key: 'Motueka', label: 'Motueka' },
          { key: 'Murchison', label: 'Murchison' },
          { key: 'Nelson', label: 'Nelson' },
        ],
      },
      {
        key: 'Marlborough',
        label: 'Marlborough Region',
        subdivs: [
          { key: 'Blenheim', label: 'Blenheim' },
          { key: 'MalboroughSounds', label: 'Malborough Sounds' },
          { key: 'Picton', label: 'Picton' },
        ],
      },
      {
        key: 'WestCoast',
        label: 'West Coast Region',
        subdivs: [
          { key: 'Greymouth', label: 'Greymouth' },
          { key: 'Hokitika', label: 'Hokitika' },
          { key: 'Westport', label: 'Westport' },
        ],
      },
      {
        key: 'Canterbury',
        label: 'Canterbury Region',
        subdivs: [
          { key: 'Amberley', label: 'Amberley' },
          { key: 'Ashburton', label: 'Ashburton' },
          { key: 'Belfast', label: 'Belfast' },
          { key: 'Cheviot', label: 'Cheviot' },
          { key: 'ChristchurchCity', label: 'Christchurch City' },
          { key: 'Darfield', label: 'Darfield' },
          { key: 'Fairlie', label: 'Fairlie' },
          { key: 'Ferrymead', label: 'Ferrymead' },
          { key: 'Geraldine', label: 'Geraldine' },
          { key: 'Halswell', label: 'Halswell' },
          { key: 'HanmerSprings', label: 'Hanmer Springs' },
          { key: 'Kaiapoi', label: 'Kaiapoi' },
          { key: 'Kaikoura', label: 'Kaikoura' },
          { key: 'Lyttelton', label: 'Lyttelton' },
          { key: 'MtCook', label: 'Mt Cook' },
          { key: 'Rangiora', label: 'Rangiora' },
          { key: 'Rolleston', label: 'Rolleston' },
          { key: 'Selwyn', label: 'Selwyn' },
        ],
      },
      {
        key: 'TimaruOtago',
        label: 'Timaru-Otago Region',
        subdivs: [
          { key: 'Kurow', label: 'Kurow' },
          { key: 'Oamaru', label: 'Oamaru' },
          { key: 'Timaru', label: 'Timaru' },
          { key: 'Twizel', label: 'Twizel' },
          { key: 'Waimate', label: 'Waimate' },
        ],
      },
      {
        key: 'Otago',
        label: 'Otago Region',
        subdivs: [
          { key: 'Alexandra', label: 'Alexandra' },
          { key: 'Balclutha', label: 'Balclutha' },
          { key: 'Cromwell', label: 'Cromwell' },
          { key: 'Dunedin', label: 'Dunedin' },
          { key: 'Lawrence', label: 'Lawrence' },
          { key: 'Milton', label: 'Milton' },
          { key: 'Palmerston', label: 'Palmerston' },
          { key: 'Queenstown', label: 'Queenstown' },
          { key: 'Ranfurly', label: 'Ranfurly' },
          { key: 'Roxburgh', label: 'Roxburgh' },
          { key: 'Tapanui', label: 'Tapanui' },
          { key: 'Wanaka', label: 'Wanaka' },
        ],
      },
      {
        key: 'Southland',
        label: 'Southland Region',
        subdivs: [
          { key: 'Bluff', label: 'Bluff' },
          { key: 'Edendale', label: 'Edendale' },
          { key: 'Gore', label: 'Gore' },
          { key: 'Invercargill', label: 'Invercargill' },
          { key: 'Lumsden', label: 'Lumsden' },
          { key: 'Otautau', label: 'Otautau' },
          { key: 'Riverton', label: 'Riverton' },
          { key: 'StewartIsland', label: 'Stewart Island' },
          { key: 'TeAnau', label: 'Te Anau' },
          { key: 'Tokanui', label: 'Tokanui' },
          { key: 'Winton', label: 'Winton' },
        ],
      },
    ],
  },
];
